# Generated by Django 2.2.6 on 2019-10-18 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elevation_gain', models.PositiveIntegerField()),
                ('elevation_lost', models.PositiveIntegerField()),
                ('itra', models.PositiveIntegerField()),
                ('itra_race_id', models.PositiveIntegerField()),
                ('food_point', models.PositiveIntegerField()),
                ('time_limit', models.DecimalField(decimal_places=1, max_digits=10)),
                ('race_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.RaceGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
