# Generated by Django 2.2.6 on 2019-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='itra_download_status',
            field=models.CharField(choices=[('U', 'Unready'), ('R', 'Ready'), ('S', 'Started'), ('C', 'Completed'), ('F', 'Failure')], default='U', max_length=1),
        ),
    ]
