# Generated by Django 2.2.6 on 2019-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20191025_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='nationality',
            field=models.CharField(default='Poland', max_length=100),
            preserve_default=False,
        ),
    ]
