# Generated by Django 2.2.6 on 2019-10-18 17:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_itra_download_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
            ],
            options={
                'unique_together': {('name', 'birth_year')},
            },
        ),
    ]
