# Generated by Django 2.2.6 on 2019-10-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='sex',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman'), ('o', 'Other')], default='o', max_length=1),
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_result', models.DurationField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='races.Race')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='races.Runner')),
            ],
        ),
    ]
