# Generated by Django 2.2.6 on 2019-10-29 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_runner_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionraceresult',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runner',
            name='birth_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
