# Generated by Django 2.2.6 on 2019-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20191029_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrace',
            name='runners',
            field=models.ManyToManyField(related_name='runners', through='races.PredictionRaceResult', to='races.Runner'),
        ),
    ]
