# Generated by Django 2.2.6 on 2019-11-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_predictionrace_runners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrace',
            name='prediction_race_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_races', to='races.PredictionRaceGroup'),
        ),
    ]
