# Generated by Django 2.2.6 on 2019-11-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_auto_20191125_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrace',
            name='future_event',
        ),
        migrations.RemoveField(
            model_name='predictionracegroup',
            name='event',
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_race_groups', to='races.Event'),
        ),
    ]
