# Generated by Django 2.2.6 on 2019-12-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_auto_20191125_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrace',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_races', to='races.Event'),
        ),
    ]
