# Generated by Django 2.2.6 on 2019-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_auto_20191219_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionrace',
            old_name='itra',
            new_name='itra_point',
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='itra_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'year')},
        ),
    ]
