# Generated by Django 2.2.6 on 2019-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_auto_20191219_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrace',
            name='itra_race_result_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='itra_race_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
