# Generated by Django 2.2.6 on 2019-12-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_auto_20191219_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionrace',
            old_name='elevation_gain',
            new_name='ascent',
        ),
        migrations.RenameField(
            model_name='predictionrace',
            old_name='elevation_lost',
            new_name='descent',
        ),
        migrations.RenameField(
            model_name='predictionrace',
            old_name='food_point',
            new_name='refreshment_points',
        ),
    ]
