# Generated by Django 2.2.6 on 2019-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_auto_20191219_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrace',
            name='finish_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='map_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='mount_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='ascent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='descent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='itra_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
