# Generated by Django 2.2.6 on 2019-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_auto_20191219_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionrace',
            old_name='start_date',
            new_name='race_time',
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='challenge',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='championship',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='city_finish',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='city_start',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='country_finish',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='country_start',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='participation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='pistes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='routes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrace',
            name='sentiers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
