# Generated by Django 2.2.6 on 2019-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0016_auto_20191219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrace',
            name='race_time',
            field=models.DateTimeField(),
        ),
    ]
