# Generated by Django 2.2.6 on 2019-12-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0018_auto_20191219_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionrace',
            old_name='race_time',
            new_name='race_date',
        ),
    ]
