# Generated by Django 2.2.6 on 2019-12-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0020_auto_20191220_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrace',
            name='race_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
