# Generated by Django 2.2.6 on 2019-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0021_predictionrace_race_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='itra_race_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='predictionrace',
            unique_together={('itra_race_id', 'race_date')},
        ),
    ]
