# Generated by Django 2.2.6 on 2019-12-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0022_auto_20191224_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runner',
            old_name='itra_race_id',
            new_name='itra_runner_id',
        ),
    ]
