# Generated by Django 2.2.6 on 2019-12-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0023_auto_20191224_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrace',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_race', to='races.Event'),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='prediction_race_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_race', to='races.PredictionRaceGroup'),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='runners',
            field=models.ManyToManyField(related_name='prediction_races', through='races.PredictionRaceResult', to='races.Runner'),
        ),
        migrations.AlterField(
            model_name='predictionraceresult',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionraceresult',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='races.Runner'),
        ),
        migrations.AlterField(
            model_name='predictionraceresult',
            name='time_result',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
