# Generated by Django 2.2.6 on 2019-12-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0024_auto_20191224_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrace',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_races', to='races.Event'),
        ),
        migrations.AlterField(
            model_name='predictionrace',
            name='prediction_race_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_races', to='races.PredictionRaceGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'year', 'itra_id')},
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together={('first_name', 'last_name', 'birth_year', 'itra_runner_id')},
        ),
    ]
